[tool.poetry]
name = "pretalx_wrapper"
version = "0.1.0"
description = ""
authors = ["adisbladis <adisbladis@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
pretalx = "^1.1.2"
psycopg2-binary = "^2.8"
dj-static = "^0.0.6"
django-redis = "^4.12"
#django-scopes = "^1.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=1.0.5"]
# poetry 1.0.9 is stable Jun 9th
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
pretalx = "pretalx_wrapper:main"
